dataSource:
  mysql:
    username: root
    password: 124563
    host: 127.0.0.1
    port: 3306
    timeLoc: Asia/Shanghai
    database: fileserver
    maxIdle: 10
    maxOpenConn: 100
    maxLifeTime: 720
business:
  userPasswordSalt: 1104459

micro:
  registration:
    consul:
      addr: 192.168.47.132:8500
  client:
    auth:
      serviceName: go.micro.service.auth
