dataSource:
  mysql:
    username: root
    password: 124563
    host: 127.0.0.1
    port: 3306
    timeLoc: Asia/Shanghai
    database: fileserver

mq:
  rabbit:
    url: amqp://guest:guest@192.168.47.132:5672/
    exchangeName: uploadserver.trans
    cephQueueName: uploadserver.trans.ceph
    cephErrQueueName: uploadserver.trans.ceph.err
    cephRoutingKey: ceph
    cephErrRoutingKey: ceph.err

business:
  uploadServiceEndpoint: http://localhost:9000
  fileStorePath: E:/go/go-disk/filestore/

micro:
  registration:
    consul:
      addr: 192.168.47.132:8500
  client:
    auth:
      serviceName: go.micro.service.auth
    download:
      serviceName: go.micro.service.download
    file:
      serviceName: go.micro.service.file
    upload:
      serviceName: go.micro.service.upload
    user:
      serviceName: go.micro.service.user