business:
  uploadServiceEndpoint: http://localhost:9000
  fileStorePath: E:/go/go-disk/filestore/

micro:
  registration:
    consul:
      addr: 192.168.47.132:8500
  client:
    auth:
      serviceName: go.micro.service.auth
    download:
      serviceName: go.micro.service.download
    file:
      serviceName: go.micro.service.file
    upload:
      serviceName: go.micro.service.upload
    user:
      serviceName: go.micro.service.user